name: myapp
description: NovelHub Project by Abi


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  rename: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 16

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/layouts/images/bjg-1.png
    - assets/layouts/images/frame-11808764.png
    - assets/layouts/images/plus-sq-fr.png
    - assets/layouts/images/frame-11808764-dSx.png
    - assets/layouts/images/px-down-arrow-3.png
    - assets/layouts/images/record273996-removebg-preview-1-1.png
    - assets/layouts/images/frame-11808764-bwN.png
    - assets/layouts/images/gshs-1.png
    - assets/layouts/images/icons-24px-solid-loader.png
    - assets/layouts/images/vector.png
    - assets/layouts/images/plus-sq-fr-CcY.png
    - assets/layouts/images/frame-11808742-bg.png
    - assets/apple-store/images/image-98.png
    - assets/layouts/images/frame-11808742.png
    - assets/layouts/images/frame-11808742-1Fv.png
    - assets/apple-store/images/frame-11808764-YKi.png
    - assets/layouts/images/frame-11808742-bg-3kk.png
    - assets/layouts/images/px-arrow-with-short-line-big.png
    - assets/layouts/images/frame-11808742-bg-4Fr.png
    - assets/apple-store/images/image-94.png
    - assets/apple-store/images/frame-11808763.png
    - assets/layouts/images/frame-11808742-bg-Rc4.png
    - assets/layouts/images/frame-11808742-68x.png
    - assets/layouts/images/frame-11808742-bg-VKW.png
    - assets/apple-store/images/frame-11808764-u3e.png
    - assets/apple-store/images/frame-11808778.png
    - assets/layouts/images/frame-11808742-iNL.png
    - assets/apple-store/images/flags.png
    - assets/apple-store/images/vector-72.png
    - assets/layouts/images/frame-11808742-TpL.png
    - assets/apple-store/images/image-95.png
    - assets/apple-store/images/plus-sq-fr-G4G.png
    - assets/apple-store/images/image-96.png
    - assets/apple-store/images/frame-11808742-bg-nwi.png
    - assets/apple-store/images/flags-ctp.png
    - assets/layouts/images/frame-11808742-eW4.png
    - assets/layouts/images/frame-11808742-rrL.png
    - assets/layouts/images/frame-11808742-ukc.png
    - assets/layouts/images/frame-11808764-TGL.png
    - assets/apple-store/images/put-your-image-here-3-1-1.png
    - assets/layouts/images/frame-11808742-bg-fdA.png
    - assets/layouts/images/record273996-removebg-preview-1-1-twA.png
    - assets/layouts/images/frame-11808763-K4k.png
    - assets/apple-store/images/flags-k7z.png
    - assets/apple-store/images/image-99.png
    - assets/layouts/images/vector-ea4.png
    - assets/layouts/images/vector-26k.png
    - assets/layouts/images/frame-11808742-bg-CGg.png
    - assets/layouts/images/rectangle-19999.png
    - assets/layouts/images/frame-11808742-EFJ.png
    - assets/layouts/images/frame-11808742-KFN.png
    - assets/layouts/images/record273996-removebg-preview-1-1-foe.png
    - assets/apple-store/images/plus-sq-fr-o8U.png
    - assets/apple-store/images/iphone-status-bar.png
    - assets/layouts/images/frame-11808742-bg-FdJ.png
    - assets/apple-store/images/frame-11808763-HTW.png
    - assets/layouts/images/plus-sq-fr-jo6.png
    - assets/layouts/images/rectangle-19999-7Uk.png
    - assets/apple-store/images/vector-73.png
    - assets/layouts/images/frame-11808742-6s2.png
    - assets/apple-store/images/vector-73-qbW.png
    - assets/layouts/images/vector-2Ak.png
    - assets/apple-store/images/iphone-status-bar-BNQ.png
    - assets/layouts/images/rectangle-20000.png
    - assets/layouts/images/plus-sq-fr-biY.png
    - assets/apple-store/images/vector-73-mur.png
    - assets/layouts/images/vector-rNt.png
    - assets/layouts/images/frame-11808742-tPJ.png
    - assets/apple-store/images/image-93.png
    - assets/apple-store/images/px-close-cancel-cross-big.png
    - assets/apple-store/images/.png
    - assets/layouts/images/frame-11808764-nVE.png
    - assets/layouts/images/rectangle-20000-xBz.png
    - assets/apple-store/images/frame-11808783.png
    - assets/layouts/images/frame-11808764-ZcC.png
    - assets/layouts/images/frame-11808742-1cL.png
    - assets/layouts/images/frame-11808764-tjA.png
    - assets/apple-store/images/flags-136.png
    - assets/apple-store/images/frame-11808742-FPn.png
    - assets/apple-store/images/px-arrow-with-short-line-right.png
    - assets/apple-store/images/frame-11808742-PM2.png
    - assets/layouts/images/frame-11808742-nwz.png
    - assets/layouts/images/auto-group-ebry.png
    - assets/apple-store/images/iphone-status-bar-QAU.png
    - assets/layouts/images/frame-11808742-pQY.png
    - assets/layouts/images/frame-11808742-WdE.png
    - assets/apple-store/images/vector-73-UK2.png
    - assets/apple-store/images/frame-11808742-bg-4Kr.png
    - assets/apple-store/images/frame-11808742-bg-3sn.png
    - assets/apple-store/images/frame-11808742-gUp.png
    - assets/apple-store/images/put-your-image-here-3-1-1-cYY.png
    - assets/layouts/images/ellipse-220.png
    - assets/apple-store/images/frame-11808742-r6C.png
    - assets/apple-store/images/frame-11808742-BDa.png
    - assets/apple-store/images/frame-11808742-4pY.png
    - assets/apple-store/images/image-100.png
    - assets/apple-store/images/frame-11808742-TUt.png
    - assets/layouts/images/frame-11808742-3nQ.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
